# Generated by Django 4.2.30 on 2026-04-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('written_test', 'Written Test'), ('gd', 'Group Discussion'), ('technical', 'Technical Interview'), ('hr', 'HR Round'), ('placed', 'Placed'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
