# Generated by Django 4.2.30 on 2026-05-01 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_application_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewschedule',
            options={'ordering': ['-scheduled_at']},
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='portal.application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Optional: For virtual interviews', null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='room_location',
            field=models.CharField(blank=True, help_text='Optional: For offline interviews', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='mode',
            field=models.CharField(choices=[('written_test', 'Written Test'), ('gd', 'Group Discussion'), ('technical', 'Technical Interview'), ('hr', 'HR Round')], max_length=25),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='round_type',
            field=models.CharField(choices=[('written_test', 'Written Test'), ('gd', 'Group Discussion'), ('technical', 'Technical Interview'), ('hr', 'HR Round')], max_length=20),
        ),
    ]
