# Generated by Django 4.2.30 on 2026-05-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_interviewschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('written_test', 'Written Test'), ('gd', 'Group Discussion'), ('technical', 'Technical Interview'), ('hr', 'HR Round'), ('placed', 'Placed'), ('rejected', 'Rejected'), ('withdrawn', 'Auto-Withdrawn (Placed Elsewhere)')], default='applied', max_length=20),
        ),
    ]
