# Generated by Django 4.2.30 on 2026-05-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_application_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='application_deadline',
            field=models.DateTimeField(),
        ),
    ]
